"""bot.db — facade re-exporting the full former bot/db.py API.

DB_PATH lives here so tests can monkeypatch bot.db.DB_PATH; all submodules
read it at call time via core.db_path().
"""
from __future__ import annotations

DB_PATH = "hde_bot.db"

from .core import (
    CachedTopicMedia,
    KnowledgeItem,
    ReplyDraft,
    SentHdeMessage,
    TICKET_TOPIC_COLUMNS,
    TicketTopic,
    UPDATABLE_FIELDS,
    _EQUIPMENT_NORM,
    _ensure_ticket_topic_columns,
    _migrate_legacy_ticket_topics,
    _row_to_cached_topic_media,
    _row_to_draft,
    _row_to_topic,
    _table_columns,
    connect,
    db_path,
    init_db,
    logger,
    migrate_feedback_samples,
    normalize_equipment,
)
from .topics import (
    _count_topics,
    append_photo_descriptions,
    clear_pre_sla,
    count_active_topics,
    count_pending_delete_topics,
    count_pending_pre_sla_topics,
    count_total_topics,
    delete_processed_event,
    get_common_env_for_company,
    get_topic,
    get_topic_by_topic_id,
    list_active_pre_sla,
    list_active_topics,
    list_due_deletions,
    list_due_pre_sla,
    list_overnight_assigned,
    list_topics_by_state,
    list_topics_missing_summary,
    mark_pre_sla_sent,
    mark_topic_deleted,
    save_processed_event,
    schedule_pre_sla,
    set_topic_active,
    set_topic_pending_delete,
    update_topic,
    upsert_topic,
    was_processed,
)
from .media import (
    cache_topic_media,
    delete_reply_draft,
    delete_sent_message,
    delete_topic_media_cache,
    gc_stale_media_cache,
    get_reply_draft,
    get_sent_message,
    list_cached_topic_media_group,
    save_reply_draft,
    save_sent_message,
)
from .misc import (
    _ensure_pending_general_table,
    clear_report_sent,
    count_general_messages,
    delete_general_message,
    delete_pending_general,
    get_general_message,
    get_setting,
    is_report_sent,
    list_general_messages,
    list_pending_general,
    mark_report_sent,
    save_general_message,
    save_pending_general,
    set_setting,
)
from .knowledge import (
    count_items_without_embedding,
    count_knowledge_by_source,
    dedup_knowledge_items,
    delete_ai_feedback_pending,
    delete_knowledge_item_by_ticket,
    expire_stale_knowledge,
    fts_search_knowledge,
    get_ai_feedback_pending,
    get_knowledge_metrics,
    get_last_knowledge_item_date,
    list_all_knowledge_embeddings,
    list_items_without_company,
    list_knowledge_content_hashes,
    list_knowledge_items_without_embedding,
    mark_knowledge_items_analyzed,
    save_ai_feedback_pending,
    save_knowledge_item,
    update_knowledge_company,
    update_knowledge_embedding,
    update_knowledge_embeddings,
    update_knowledge_last_used,
    upsert_knowledge_item,
)
from .patterns import (
    build_pattern_index,
    count_solution_patterns_by_equipment,
    find_solution_pattern,
    increment_pattern_use,
    list_solution_patterns,
    pattern_exists_similar,
    pattern_similar_in_index,
    save_solution_pattern,
)
from .optimizer_store import (
    apply_prompt_version,
    get_active_prompt,
    get_optimization_samples,
    get_prompt_version,
    list_prompt_versions,
    reject_all_prompt_candidates,
    save_optimization_sample,
    save_prompt_version,
)
from .suggestion_store import (
    collect_suggestion_daily_stats,
    compute_idempotency_key,
    derive_human_label,
    get_open_suggestion_by_topic,
    get_suggestion,
    record_suggestion,
    record_suggestion_event,
)
from .dialogue_store import (
    count_dialogue_pairs,
    count_pairs_by_quality,
    dialogue_pair_hashes,
    list_fewshot_candidates,
    list_pairs_for_gating,
    list_pending_embeddings,
    list_processed_ticket_ids,
    log_ticket_error,
    mark_ticket_processed,
    save_dialogue_pair,
    set_pair_embedding,
    set_pair_quality,
)
